# Generated by Django 5.0.6 on 2024-06-19 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('Processing', 'В процессе'), ('Completed', 'Готов'), ('Pending', 'Принят')], default='Pending', max_length=10, verbose_name='Статус заказа'),
        ),
    ]
