# Generated by Django 5.0.6 on 2024-06-14 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('Processing', 'Processing'), ('Pending', 'Pending'), ('Completed', 'Completed')], default='Pending', max_length=10, verbose_name='Статус заказа'),
        ),
    ]
