# Generated by Django 5.0.6 on 2024-06-20 06:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0002_alter_order_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('Pending', 'Принят'), ('Completed', 'Готов'), ('Processing', 'В процессе')], default='Pending', max_length=10, verbose_name='Статус заказа'),
        ),
    ]
